### ISSUE TITLE
Any guide for using BurpAttacks ? 

### ISSUE THREAD

**Issue by qt00tp** [1N3/IntruderPayloads#1]
Need help, could you please show me the right method for using the BurpAttacks?

**Comment by 1N3** [comment]
From Burpsuite Intruder, go to Intruder menu > Load Attack Config > Without payload position and select the attack config file you want to use. Then highlight the location or parameter you want to fuzz and click the "Start Attack" button to start. 

I will update the README as well with instructions.

**Comment by qt00tp** [comment]
Thank you for your help. It's working.

**Comment by 1N3** [comment]
Cool, no prob!
