### ISSUE TITLE
Error upload config file

### ISSUE THREAD

**Issue by satanvraw** [1N3/IntruderPayloads#6]
Hey Brothers!

I dont know why my burp isnt get the file

Here is the output:

![x](https://user-images.githubusercontent.com/44817193/48088227-926bca00-e1e8-11e8-8823-fcb4d1484bf9.png)

**Comment by 1N3** [comment]
Hi, Which file(s) are you trying to load? There's a few different types of config files in the repo which require different steps to use.

**Comment by satanvraw** [comment]
Hi 1N3, 

The file is on IntruderPayloads/Burpattacks/burp_config and burpconfig_default, I extract and I load into Intruder/Loadattack config/without payload config.

Tks bro

**Comment by satanvraw** [comment]
The file that was extracted is called burp, I load this file... I dont know if is this file
