### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by quarinteen** [1N3/IntruderPayloads#8]
Hello I sorry for creating an issue. I was just hoping you guys might be able to create some documentation or a tutorial on how to use this content? I am new with Burp Pro and it would be very helpful. If you know of some good documents or tutorials please let me know. Thank you.

**Comment by Saiprakashreddy14** [comment]
Sure .we will look into it and get back to you

**Comment by chppppp** [comment]
+1 for a newb guide!

**Comment by geeknik** [comment]
Enjoy.

[Beginner's guide to  Burp payloads Part 1](https://www.hackingarticles.in/beginners-guide-burpsuite-payloads-part-1/)

[Beginner's guide to  Burp payloads Part 2](https://www.hackingarticles.in/beginners-guide-burpsuite-payloads-part-2/)

[Burp -> Documentation -> Tools -> Intruder -> Payloads](https://portswigger.net/burp/documentation/desktop/tools/intruder/payloads)

[Burp Intruder attack types](https://www.sjoerdlangkemper.nl/2017/08/02/burp-intruder-attack-types/)

[Burp Intruder payload methods explained ](https://danielmiessler.com/blog/burp-intruder-payloads/)

[Burp Suite Tutorial - Intruder Attack with Simple list Payload set](https://www.youtube.com/watch?v=c0h3aciBIyQ)

[Configuring a Burp Intruder attack](https://support.portswigger.net/customer/portal/articles/1783129-configuring-a-burp-intruder-attack)

[How to Burp good](https://www.n00py.io/2017/10/how-to-burp-good/)
