### ISSUE TITLE
How to import BurpBountyPayloads ?

### ISSUE THREAD

**Issue by chppppp** [1N3/IntruderPayloads#9]
I am struggling to import the BurpBountyPayloads. They appear to be ACTIVE/PASSIVE scan configs but I cannot figure out where to import them. They do not import into Intruder, I get errors `Error loading saved configuration` and `Error opening saved attack: File is not in correct format`. 

Your help is appreciated :) Thank you.

**Comment by chppppp** [comment]
Do you need the Burp Bounty extension for this?????

**Comment by clobee** [comment]
@chppppp have you tried Intruder > Payloads > then loads button?

**Comment by 1N3** [comment]
@chppppp Yes, you need the burp bounty extension for the active/passive scan configs.
